service: service-for-test

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    SECRET_ACCESS_KEY: ${self:custom.secrets.SECRET_ACCESS_KEY}
    ACCESS_KEY: ${self:custom.secrets.ACCESS_KEY}
  package:
    individually: true
    exclude:
      - node_modules/**

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  secrets: ${file(./secrets.json)}

functions:
  accessControl:
    handler: src/functions/auth/accessControl.accessControlHandler
  createUser:
    handler: src/functions/user/createUser.createUserHandler
    events:
      - http:
          path: createUser
          method: post
          cors: true
          authorizer:
            name: accessControl
            identitySource: method.request.header.Authorization
            type: token
            resultTtlInSeconds: 3600
  login:
    handler: src/functions/auth/login.loginHandler
    events:
      - http:
          path: login
          method: post
          cors: true
  createPost:
    handler: src/functions/post/createPost.createPostHandler
    events:
      - http:
          path: cms/createPost
          method: post
          authorizer: accessControl
  savePost:
    handler: src/functions/post/savePost.savePostHandler
    events:
      - sqs: arn:aws:sqs:us-east-1:487009629625:queue
  getPost:
    handler: src/functions/post/getOnePost.getOnePostHandler
    events:
      - http:
          path: cms/post
          method: get
          request:
            template:
              application/json: >
                {
                  "id": "$input.params('id')"
                }
  getAllPosts:
    handler: src/functions/post/getAllPosts.getAllPostsHandler
    events:
      - http:
          path: cms/posts
          method: get
  deletePost:
    handler: src/functions/post/deletePost.deletePostHandler
    events:
      - http:
          path: cms/deletePost
          method: delete
          authorizer: accessControl
  updatePost:
    handler: src/functions/post/updatePost.updatePostHandler
    events:
      - http:
          path: cms/updatePost
          method: put
          authorizer: accessControl
